### ISSUE TITLE
UserNotFound and UsernameNotAvailable are not getting their name set correctly

### ISSUE THREAD

**Issue by pekeler** [arangodb-foxx/util-users-local#1]
The names are currently set to "Error" which means I can't catch it with

``` javascript
.errorResponse('UsernameNotAvailable', 409, 'Email is already taken.')
```

in my controller.

**Comment by pluma** [comment]
Thanks for the heads-up. I've adjusted the error types here and in foxx-sessions and foxx-sessions-jwt accordingly. I've also added a small test runner wrapper to enable testing these apps inside ArangoDB on travis.

**Comment by pekeler** [comment]
Great - thanks!
